FROM webdevops/php-nginx


#ENV HOST_NAME dockerhostname 
#ENV DB_ADDRESS dockerdbaddress
#ENV DB_USERNAME dockerdbusername
#ENV DB_PASSWORD dockerdbpasswor
#ENV DB_NAME dockerdbname

COPY ./index.php /app
