---
- hosts: db_server
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: true

  

  tasks:
    - name: Copying database file
      copy:
        src: ./Database/database.sql
        dest: /tmp
     
    - name: Install MySQL
      apt:
        name: mysql-server
        update_cache: yes
        state: present
     
    - name: Instal python package for mysql
      apt:     
        name: python-mysqldb
        update_cache: yes
        state: present

    - name: Restore database
      mysql_db:
        name: "{{ lookup('env','DB_NAME') }}"
        state: import
        target: /tmp/database.sql


    - name: Copying mysql config file
      copy: 
        src: ./Database/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf

    - name: update mysql root password
      mysql_user:
        name: root
        host: "{{ item }}"
        password: password
        login_user: root
        login_password: password
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
        host: "%"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create app user
      mysql_user:
        host: "{{ item }}"
        login_user: root
        login_password: password
        name: "{{ lookup('env','DB_USERNAME') }}"
        password: "{{ lookup('env','DB_PASSWORD') }}"
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost


    - name: Start the MySQL service
      service:
        name: mysql
        state: started
        enabled: true

    - name: Restart the MySQL service
      service:
        name: mysql
        state: restarted
