---
- hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars:
    default_container_name: docker
    default_container_image: piotrzalecki/exercise
  

  tasks:
    - name: Install pip
      apt: name=python-pip state=present
      
    - name: Install Docker Module for Python
      pip:
        name: docker-py

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        ports:
        - "80:80"
        - "443:443"
        env:
          HOST_NAME: "{{ lookup('env','HOST_NAME') }}"        
          DB_ADDRESS: "{{ lookup('env','DB_ADDRESS') }}"
          DB_USERNAME: "{{ lookup('env','DB_ADDRESS') }}"
          DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
          DB_NAME: "{{ lookup('env','DB_NAME') }}"
