---
- hosts: web_server
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: true
  vars:
    default_container_name: docker
    default_container_image: piotrzalecki/exercise
  

  tasks:
    - name: Install pip
      apt: 
        name: python-pip
        state: present
#        update_cache: yes
      
    - name: Install Docker Module for Python
      pip:
        name:
         -  docker
         -  request>=2.20.1
        executable: /usr/bin/pip

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        ports:
        - "80:80"
        - "443:443"
        env:
          HOST_NAME: "{{ ansible_nodename }}"        
          DB_ADDRESS: "{{ dbaddress }}"
          DB_USERNAME: "{{ lookup('env','DB_USERNAME') }}"
          DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
          DB_NAME: "{{ lookup('env','DB_NAME') }}"
